version: 2.1

jobs:
  build-service:
    docker:
      - image: alexfalkowski/go:2.17
    working_directory: ~/sasha
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - restore_cache:
          name: restore go deps
          keys:
            - sasha-go-cache-{{ checksum "go.sum" }}
            - sasha-go-cache-
      - restore_cache:
          name: restore ruby deps
          keys:
            - sasha-ruby-cache-{{ checksum "test/Gemfile.lock" }}
            - sasha-ruby-cache-
      - run: make clean
      - run: make dep
      - save_cache:
          name: save go deps
          key: sasha-go-cache-{{ checksum "go.sum" }}
          paths:
            - /home/circleci/go/pkg/mod
      - save_cache:
          name: save ruby deps
          key: sasha-ruby-cache-{{ checksum "test/Gemfile.lock" }}
          paths:
            - test/vendor
      - restore_cache:
          name: restore go build cache
          keys:
            - sasha-go-build-cache-{{ checksum "go.sum" }}
            - sasha-go-build-cache-
      - run: make clean
      - run: make lint
      - run: make sec
      - run: make features
      - run: make benchmarks
      - run: make analyse
      - save_cache:
          name: save go build cache
          key: sasha-go-build-cache-{{ checksum "go.sum" }}
          paths:
            - /home/circleci/.cache/go-build
      - run: make coverage
      - store_test_results:
          path: test/reports
      - store_artifacts:
          path: test/reports
      - run: make codecov-upload
    resource_class: large
  build-docker:
    docker:
      - image: alexfalkowski/go:2.17
    working_directory: ~/sasha
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - setup_remote_docker:
          docker_layer_caching: true
      - run: make build-docker
      - run: make trivy
    resource_class: large
  release:
    docker:
      - image: alexfalkowski/release:3.19
    working_directory: ~/sasha
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: make pull
      - run: release
    resource_class: large
  push-docker:
    docker:
      - image: alexfalkowski/go:2.17
    working_directory: ~/sasha
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: make pull
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: make login
          command: echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      - run: make push-docker
    resource_class: large

workflows:
  sasha:
    jobs:
      - build-service
      - build-docker:
          context: gh
      - release:
          context: gh
          requires:
            - build-service
            - build-docker
          filters:
            branches:
              only: master
      - push-docker:
          context: docker
          requires:
            - release
          filters:
            branches:
              only: master
